#!/bin/bash
# ----------------------------------------------------------------------------
# /var/install/config.d/quassel-core - QUASSEL_CORE configuration
#
# Creation   : 2009-12-14 Marcel Weiler
#
# Copyright (c) 2001-2013 The eisfair Team, <team(at)eisfair(dot)org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# ----------------------------------------------------------------------------

#exec 2> /tmp/quassel-core-trace$$.log
#set -x

# set package name
packageName=quassel-core
binaryName=quasselcore-static-0.8.0
linkName=quasselcore

# ----------------------------------------------------------------------------
# Includes
# ----------------------------------------------------------------------------

# include eislib
. /var/install/include/eislib

# include config
. /etc/config.d/${packageName}

# ----------------------------------------------------------------------
# Default variables (not user changeable)
# ----------------------------------------------------------------------
packagePosition=98

# ----------------------------------------------------------------------
# Functions
# ----------------------------------------------------------------------
_add_rc_symlinks()
{
    packageStart="S${packagePosition}${packageName}"
    packageKill="K$(expr 100 - ${packagePosition})${packageName}"
	
    ln -sf /etc/init.d/${packageName} /etc/rc2.d/${packageStart}
    ln -sf /etc/init.d/${packageName} /etc/rc2.d/${packageKill}
}

_delete_rc_symlinks()
{
    rm -f /etc/rc2.d/S??${packageName}
    rm -f /etc/rc2.d/K??${packageName}
}

_edit_logrotate_file()
{
    creationTime=`date --iso-8601='seconds'`
    
        {
	    echo '# ----------------------------------------------------------------------------'
    	    echo "# /etc/logrotate.d/${packageName} created by ${0}"
	    echo '#'
    	    echo '# DO NOT EDIT THIS FILE BY HAND! (use eisfair setup!)'
    	    echo '#'
    	    echo "# Created: ${creationTime}"
    	    echo '# ----------------------------------------------------------------------------'
    	    echo "/var/log/${packageName}/core.log {"
        } > /etc/logrotate.d/${packageName}

        cat >> /etc/logrotate.d/${packageName} <<-EOFG
        rotate ${QUASSEL_CORE_LOG_COUNT}
        ${QUASSEL_CORE_LOG_INTERVAL}
        compress
        delaycompress
        copytruncate
        missingok
        notifempty
	}
EOFG
}



setupSymlinkForBinary ()
{
    cd /usr/local/quassel-core/bin
    if [ -L "$linkName" ] ; then
        rm -f $linkName
    fi
    ln -s $binaryName $linkName
}



# ----------------------------------------------------------------------------
# Main
# ----------------------------------------------------------------------------

# add symlinks if quassel-core is configured to start automatically
if [ "${START_QUASSEL_CORE}" = 'yes' ] ; then
    _add_rc_symlinks
else
    _delete_rc_symlinks
fi

# change logrotate file to actual config settings
_edit_logrotate_file

setupSymlinkForBinary

exit 0
# ----------------------------------------------------------------------------
# End
# ----------------------------------------------------------------------------
