#! /bin/bash
#----------------------------------------------------------------------------------
# /var/install/bin/quassel-core-change-userpass - change password of a quassel-core user
#
# Copyright (c) 2001-2010 The Eisfair Team, team(at)eisfair(dot)org
#
# Creation:     23.12.2009  marwe
# Last Update:  $Id: quassel-core-change-userpass 23575 2010-03-22 21:06:57Z marwe $
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#----------------------------------------------------------------------------------

# read eislib
. /var/install/include/eislib

# defaults
QUASSEL_CORE_CONFIGDIR=/data/packages/quassel-core/

# ask for username and call change-pass function with it
USER_INPUT=`/var/install/bin/ask "Name of User to change Password" "" "+"`

/usr/local/quassel-core/bin/quasselcore --change-userpass=${USER_INPUT} -c ${QUASSEL_CORE_CONFIGDIR}
