#! /bin/bash
#----------------------------------------------------------------------------------
# /var/install/bin/quassel-core-add-user - add user to quassel-core database
#
# Copyright (c) 2001-2010 The Eisfair Team, team(at)eisfair(dot)org
#
# Creation:     23.12.2009  marwe
# Last Update:  $Id: quassel-core-add-user 23575 2010-03-22 21:06:57Z marwe $
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#----------------------------------------------------------------------------------

# read eislib
. /var/install/include/eislib

# defaults
QUASSEL_CORE_CONFIGDIR=/data/packages/quassel-core/

# start add-user function of core, its interactive
/usr/local/quassel-core/bin/quasselcore --add-user -c ${QUASSEL_CORE_CONFIGDIR}
