#!/sbin/runscript
# init.d file for alpine linux.

name=smc-milter-new
daemon=/usr/sbin/$name

depend() {
	need net
	after firewall
}

start() {
	ebegin "Starting ${name}"
		start-stop-daemon --start --quiet \
			--pidfile /run/${name}.pid \
			--chuid ${sample_user}:${sample_group} \
			--exec ${daemon} -- ${sample_opts}
	eend $?
}

stop() {
	ebegin "Stopping ${name}"
		start-stop-daemon --stop --quiet \
			--pidfile /run/$name.pid \
			--exec ${daemon}
	eend $?
}

