<?php

$labels = array();
$labels['forwardtitle'] = 'Weiterleitung';
$labels['forwardsubject'] = 'Kopfzeile';
$labels['forwardmessage'] = 'weiterleiten an';
$labels['forwardexpires'] = 'Expires';
$labels['forwarddatefrom'] = 'g&uuml;ltig ab';
$labels['forwarddateto'] = 'g&uuml;ltig bis';
$labels['forwardenabled'] = 'aktiviert';
$labels['dateformat'] = 'Tag Monat Jahr';
$labels['and'] = 'and';
$labels['missingmail'] = 'Eine gueltige E-Mail Adresse fehlt!';

$messages = array();
$messages['dateformatinconsistency'] = 'Datum ist nicht korrekt';
$messages['entervalidmonth'] = 'Enter a valid month.';
$messages['entervalidday'] = 'Enter a valid day.';
$messages['enterfordigityear'] = 'Enter four digit year between';
$messages['entervaliddate'] = 'Enter a valid date.';
$messages['dateinpast'] = 'Date not in future. Expiration will be disabled!';
$messages['subjectempty'] = 'Please enter a subject';
$messages['demoaccount'] = 'This is a Demo Account. Away message is disallowed.';
$messages['missingmail'] = 'Eine gueltige E-Mail Adresse fehlt!';

?>
