<?php

$labels = array();
$labels['forwardtitle'] = 'Forwarding';
$labels['forwardsubject'] = 'Subject';
$labels['forwardmessage'] = 'forward to';
$labels['forwardexpires'] = 'Expires';
$labels['forwarddateto'] = 'Date';
$labels['forwarddatefrom'] = 'Valid since';
$labels['forwardenabled'] = 'Enabled';
$labels['dateformat'] = 'yyyy/mm/dd';
$labels['and'] = 'and';
$labels['missingmail'] = 'Missing e-mail address!';

$messages = array();
$messages['dateformatinconsistency'] = 'Date format is inconsistent';
$messages['entervalidmonth'] = 'Enter a valid month.';
$messages['entervalidday'] = 'Enter a valid day.';
$messages['enterfordigityear'] = 'Enter four digit year between';
$messages['entervaliddate'] = 'Enter a valid date.';
$messages['dateinpast'] = 'Date not in future. Expiration will be disabled!';
$messages['subjectempty'] = 'Please enter a subject';
$messages['demoaccount'] = 'This is a Demo Account. Away message is disallowed.';
$messages['missingmail'] = 'Missing e-mail address!';
?>
