#!/bin/sh
#----------------------------------------------------------------------------
# /var/install/config.d/apk-repositories.sh - apply configuration 
# Copyright (c) 2001-2014 the eisfair team, team(at)eisfair(dot)org
# Creation:     2013-05-03 starwarsfan
#----------------------------------------------------------------------------

package_name=apk-repositories

#exec 2>/tmp/${package_name}-trace$$.log
#set -x

. /etc/config.d/$package_name

# ----------------------------------------------------------------------------
# Create apk repo configuration /etc/apk/repositories
# ----------------------------------------------------------------------------
cat > /etc/apk/repositories <<EOF
# ----------------------------------------------------------------------------
# Config file generated by eisfair-ng setup
# Do not edit this file, edit /etc/config.d/apk-repositories
# ----------------------------------------------------------------------------

EOF

# Begin idx -le ${APK_REPOSITORY_N}
idx=1
while [ "${idx}" -le "${APK_REPOSITORY_N}" ] ; do
    eval active='${APK_REPOSITORY_'${idx}'_ACTIVE}'
    eval host='${APK_REPOSITORY_'${idx}'_URL}'
    if [ "${active}" = 'yes' ] ; then
        commentCharacter=''
    else
        commentCharacter='#'
    fi

    echo ${commentCharacter}${host} >> /etc/apk/repositories

    # End idx -le ${APK_REPOSITORY_N}
    idx=`/usr/bin/expr ${idx} + 1`
done

echo "Apk repository configuration written."

exit 0
