#!/bin/sh
#-------------------------------------------------------------------------------
# Eisfair configuration generator script
# Copyright (c) 2007 - 2015 the eisfair team, team(at)eisfair(dot)org
#-------------------------------------------------------------------------------

#echo "Executing $0 ..."
#exec 2> /tmp/ssmtp-trace$$.log
#set -x

# read base configuration file for domain
. /etc/config.d/base

. /etc/config.d/dhcp

#-------------------------------------------------------------------------------
# creating/edit config file
#-------------------------------------------------------------------------------
{
    echo "#----------------------------------------------------------------------"
    echo "# Do not edit this file directly, modify '/etc/config.d/dhcp' file and"
    echo "# re-run the /var/install/config.d/dhcp.sh' command to update."
    echo "#----------------------------------------------------------------------"
    echo ""

} > /etc/dhcp/dhcp.conf

# Set rights for configuration file
chmod 0644 /etc/dhcp/dhcp.conf
# hide plaintext password
chown root /etc/dhcp/dhcp.conf


#------------------------------------------------------------------------------
exit 0
