<?php
//Anyone fluent in German feel free to review this file
$labels = array();
$labels['vmail_user'] = 'Benutzerverwaltung';
//$labels['vmail_userdelete'] = 'Delete emails after receiving';
$labels['vmail_userenabled'] = 'Aktiv';
$labels['vmail_userfetchall'] = 'Alle eMails vom Server abrufen';
//$labels['vmail_userfolder'] = 'Remote server folder';
$labels['vmail_userkeep'] = 'Mails nach Empfang _nicht_ löschen';
$labels['vmail_userpollinterval'] = 'Häufigkeit der Mailboxabfrage in Minuten';
//$labels['vmail_userprotocol'] = 'Protocol';
//$labels['vmail_userserver'] = 'Server hostname';
$labels['vmail_userusessl'] = 'SSL bei Abruf verwenden';
$labels['vmail_user_entries'] = 'Vorhandene Einträge';
$labels['vmail_user_to'] = 'E-Mail Benutzer anlegen oder anpassen';
$labels['vmail_usereditlevel'] = 'Bearbeiter Level';
$labels['nofetch'] = 'Keine Einträge vorhanden';

$labels['vmail_userloginname']   = 'Anmeldename';
$labels['vmail_userusername']    = 'Vorname Nachname';
$labels['vmail_userdatacomment'] = 'Passwort';
$labels['vmail_usertoall']       = 'An-alle';
$labels['vmail_usersignat']      = 'Absender Signatur';
$labels['vmail_useractive']      = 'Aktiv';
$labels['vmail_userexpired']     = 'Abschaltung am';
$labels['vmail_userymd']         = 'Tag Monat Jahr';

$messages = array();
$messages['vmail_userabort'] = 'Abbrechen';
$messages['vmail_userdelconfirm'] = 'Wollen Sie diesen Eintrag wirklich löschen?';
$messages['vmail_userlimitreached'] = 'Limit erreicht';
$messages['vmail_usernewentry'] = 'Als neuen Eintrag speichern';
$messages['opnotpermitted'] = 'Operation nicht gestattet!';
$messages['successfullydeleted'] = 'Erfolgreich gelöscht!';
$messages['successfullydisabled'] = 'Erfolgreich deaktiviert!';
$messages['successfullyenabled'] = 'Erfolgreich aktiviert!';
$messages['successfullysaved'] = 'Erfolgreich gespeichert!';
$messages['textempty'] = 'Ein oder mehrere Felder sind leer';

?>
