<?php

$labels = array();
$labels['vmail_user'] = 'User managment';
$labels['vmail_userdelete'] = 'Delete emails after receiving';
$labels['vmail_userenabled'] = 'Enable';
$labels['vmail_userfetchall'] = 'Fetch all e-mails from server';
$labels['vmail_userfolder'] = 'Remote server folder';
$labels['vmail_userkeep'] = 'Do not remove messages from the server';
$labels['vmail_userpollinterval'] = 'Poll interval for the mailbox';
$labels['vmail_userprotocol'] = 'Protocol';
$labels['vmail_userserver'] = 'Server hostname';
$labels['vmail_userusessl'] = 'Use SSL';
$labels['vmail_user_entries'] = 'Accounts to collect from';
$labels['vmail_user_to'] = 'Collect mail to';
$labels['vmail_usereditlevel'] = 'Editor level';
$labels['nofetch'] = 'No entries available';

$labels['vmail_userloginname']   = 'Login name';
$labels['vmail_userusername']    = 'Username';
$labels['vmail_userdatacomment'] = 'Pass';
$labels['vmail_usertoall']       = 'To all';
$labels['vmail_usersignat']      = 'Sender signature';
$labels['vmail_useractive']      = 'Active';
$labels['vmail_userexpired']     = 'Expired';
$labels['vmail_userymd']         = 'Day Month Year';

$messages = array();
$messages['vmail_userabort'] = 'Cancel';
$messages['vmail_userdelconfirm'] = 'Do you want to delete this entry?';
$messages['vmail_userlimitreached'] = 'Limit reached';
$messages['vmail_usernewentry'] = 'Save as new';
$messages['opnotpermitted'] = 'Operation not permitted!';
$messages['successfullydeleted'] = 'Deleted successfully!';
$messages['successfullydisabled'] = 'Disabled successfully!';
$messages['successfullyenabled'] = 'Enabled successfully!';
$messages['successfullysaved'] = 'Saved successfully!';
$messages['textempty'] = 'One or more fields are empty';

?>
