NTP_GET_CLOCK_TYPE_CUI = '[1-79]|[1-3][0-9]|4[0-4]|8 [0-9]|8 1[0-7]'
                       : 'Must be a numeric value from 1-44. If value of 8 then followed by another value from 0 to 17 separated by space.'

NTP_LOG_INTERVAL_CUI   = 'daily|weekly|monthly'
                       : 'No valid interval! Must be "daily", "weekly" or "monthly".'

NTP_LOG_TYPES_CUI      = 'all|syncstatus|sysevents|syncall|clockall'
                       : 'No valid log event choosen. Must be one out "all", "syncstatus", "sysevents", "syncall" or "clockall".'
