#!/bin/sh
#-----------------------------------------------------------------------------
# /usr/sbin/setup - setup menu start script
# Copyright (c) 2001-2013 The Eisfair Team <team@eisfair.org>
#-----------------------------------------------------------------------------
cd /tmp

# call menu
/var/install/bin/show-menu.cui /var/install/menu/setup.menu
exit 0
