#!/bin/sh
#------------------------------------------------------------------------------
# /usr/sbin/setup - setup menu start script
# Creation:    2001.11.04 fm
# Last update: $Id: setup 12915 2007-12-16 17:30:44Z jv $
#------------------------------------------------------------------------------

cd /tmp

# call menu
/var/install/bin/show-menu.cui /var/install/menu/setup.menu
exit 0
