<?php

$labels = array();
$labels['autoresponder'] = 'Abwesenheitsnachricht';
$labels['autorespondersubject'] = 'Kopfzeile';
$labels['autorespondermessage'] = 'Nachricht';
$labels['autoresponderexpires'] = 'Expires';
$labels['autoresponderdatefrom'] = 'g&uuml;ltig ab';
$labels['autoresponderdateto'] = 'g&uuml;ltig bis';
$labels['autoresponderenabled'] = 'aktiviert';
$labels['dateformat'] = 'Tag Monat Jahr';
$labels['and'] = 'and';

$messages = array();
$messages['dateformatinconsistency'] = 'Datum ist nicht korrekt';
$messages['entervalidmonth'] = 'Enter a valid month.';
$messages['entervalidday'] = 'Enter a valid day.';
$messages['enterfordigityear'] = 'Enter four digit year between';
$messages['entervaliddate'] = 'Enter a valid date.';
$messages['dateinpast'] = 'Date not in future. Expiration will be disabled!';
$messages['subjectempty'] = 'Please enter a subject';
$messages['demoaccount'] = 'This is a Demo Account. Away message is disallowed.';

?>
