#!/bin/sh
#-----------------------------------------------------------------------------
# Creation:     2006-08-18 Jens Vehlhaber <jens(at)eisfair(dot)org>
#-----------------------------------------------------------------------------

#include eislib
. /var/install/include/eislib

case "$1"
in
    qlist)
        mailq >> /tmp/mailq.$$
        /var/install/bin/show-doc.cui -f /tmp/mailq.$$
        rm -f /tmp/mailq.$$
        ;;
    qflush)
        clrhome
        echo "Flush all e-mails and show mail queue:"
        /usr/sbin/postfix flush
        mailq
        anykey
        ;;
    qhandle)
        /usr/bin/pfqueue -b postfix2 -q 1
        ;;
esac

### -------------------------------------------------------------------------
exit 0
