#!/bin/sh
#-----------------------------------------------------------------------------
# Creation:     2010-05-28 Jens Vehlhaber  jv <jens(at)eisfair(dot)org>
# Last Update:  $Id: vmail-modules-maildropfilter 24675 2010-06-25 14:33:58Z jv $
#-----------------------------------------------------------------------------
clear
. /var/install/include/eislib
. /etc/config.d/vmail
if [ "$VMAIL_SQL_HOST" = 'localhost' ]; then
    vmail_sql_connect="unix:/run/mysqld/mysqld.sock"
else
    vmail_sql_connect="inet:$VMAIL_SQL_HOST"
fi
# get uid/gid for user vmail
uidvmail=$(id -u vmail)
gidvmail=$(id -g vmail)
# run
/usr/bin/mysql2sieve -v -s $vmail_sql_connect -d $VMAIL_SQL_DATABASE -u $VMAIL_SQL_USER -p $VMAIL_SQL_PASS -b $uidvmail -c $gidvmail
anykey

exit 0

