#!/bin/sh
#-----------------------------------------------------------------------------
# Creation:     2007-02-21 Jens Vehlhaber <jens(at)eisfair(dot)org>
# Last Update:  $Id: vmail-modules-fetchmail 24769 2010-06-29 05:55:57Z jv $
#-----------------------------------------------------------------------------

#include eislib
. /var/install/include/eislib

VMAIL_TLS_CAPATH='/usr/local/ssl/certs'

#include configuration
. /etc/config.d/vmail


# define fetchmailconfig file
fetchfile=".fetchmailrc.\$$"

clrhome

# use user vmail
fetchfile=".fetchmailrc.\$$"
su vmail -c "/usr/local/postfix/fetchmysql -t /var/spool/postfix/virtual/${fetchfile} \\
            -u $VMAIL_SQL_USER -s $VMAIL_SQL_HOST -d $VMAIL_SQL_DATABASE -p $VMAIL_SQL_PASS -e ${VMAIL_SQL_ENCRYPT_KEY} -v ;\\
            /usr/bin/fetchmail -v -t ${FETCHMAIL_TIMEOUT} -f /var/spool/postfix/virtual/$fetchfile --nobounce --sslcertpath $VMAIL_TLS_CAPATH --postmaster $FETCHMAIL_POSTMASTER ; \\
            rm -f /var/spool/postfix/virtual/$fetchfile"

### -------------------------------------------------------------------------
exit 0

